language: go
go:
- 1.4
addons:
  apt:
    packages:
    - rpm
deploy:
  provider: releases
  api_key:
    secure: vNX3IgrN9ssBkwafQjzMVE1TXHMjrB67ktTZZ9PhdVmg1CqnBHzb8lYQjCMA/k2dCCsGOB4+A9RZkQD16qU1MiDpa22i2hhrgwvGjlLTOr9ec22llVVsp/r4qnj42RCcP60+Eolqv+DLjQGTMKuMYqZ0RMcJY2UJVYi1j7vWEEu9QHeKmVW/hbSA9qeSYdjQbOiJAHFxY1giXZ04vbaRfuNstpobpkqwt042Rl8w2jVkqSs60UE0FUguLyQ3kovVYp4fWzTWcTIfwa3CwsLYgX4Zpf50DVL0D4zJkJEPQv+XlBbdn0oSyAa44BV6/Oh06WKZnARw9Af/uY03p2ks9dkfZhGgvZ0GGDbGWyJVykS8UwkNAdBeuoGQc+CnTGXLA0YPJQ8TCHvJlc5ZIHS01OKmwxFNn+FCM4HCTymR4S0SytK78xbBh3YXChGIkiwOreno6T7gnz84hK5g2pk6KgH4i9KgGEUQzINWniXhDlQTehVnuzEfllytGuV27RFBS5sk2C0QKV8gP0HcINUIblHggixUtSbgc+QqzaDVuz8mrf6S4ir9ph3e79Ie3JCNUzMVqJaqqwjjUwsIPx6EntPNXbXzO896R/OzKhXypw/1hkqiw9aU7DSPGEPraUVp3oaws5+GFdLL5qrPoyZEOpoBzNHCr4dEUk/5SoZBXIo=

  file:
    - "$(head -1 README.md | grep -o '^[^(]*')_$(echo $TRAVIS_TAG | grep -oE 'v[0-9.]+$' |cut -c 2- )_amd64.deb"
    - "$(head -1 README.md | grep -o '^[^(]*')-$(echo $TRAVIS_TAG | grep -oE 'v[0-9.]+$' |cut -c 2- )-1.x86_64.rpm"
    - "$(head -1 README.md | grep -o '^[^(]*')-$(echo $TRAVIS_TAG | grep -oE 'v[0-9.]+$' |cut -c 2- ).darwin_amd64"
  on:
    tags: true
